"""
Composite Simpson on a uniform grid.

``scipy.integrate.simpson`` accepts an arbitrary ``x``, and paying
for that generality turned out to dominate three of this library's
integrals. Measured on 400 points:

===============================  ========
call                                 time
===============================  ========
``simpson(y, x=grid)``            35.8 us
``simpson(y, dx=h)``              13.7 us
**this module**                  **1.9 us**
===============================  ========

The ``x=`` form is the expensive one, and it costs the same whether
the grid it is handed happens to be uniform or not -- SciPy does
not check. Every grid here is generated by ``linspace`` or
``logspace``, so uniformity is known at the call site: either
directly, or after substituting the log, which is what the
log-spaced grids are uniform in.

Worth recording, because I got this wrong once: an earlier round
dismissed ``simpson`` as cheap after timing ``simpson(y, dx=h)``.
That is a different code path from the ``simpson(y, x=grid)`` the
callers actually used, and three times faster than it. The
profiler had been right and the check was wrong.
"""

from __future__ import annotations

import numpy as np


def odd_grid(n):
    """
    Round a requested grid size up to an odd number.

    Composite Simpson needs an *even* number of intervals, so an
    odd number of points. Callers take a grid size from the user
    and pass it straight through, so the rounding happens here
    rather than being each caller's problem -- and rounding up
    never loses accuracy.
    """

    n = int(n)

    return n if n % 2 else n + 1


def simpson_uniform(y, dx):
    """
    Integrate samples on a uniform grid.

    Parameters
    ----------
    y : ndarray
        Samples at ``n`` equally spaced points, ``n`` **odd** so
        that the number of intervals is even. Not checked here;
        callers size their grids with :func:`odd_grid`.
    dx : float
        Spacing.

    Returns
    -------
    float
    """

    weights = np.empty(y.shape[-1])

    weights[0] = weights[-1] = 1.0
    weights[1:-1:2] = 4.0
    weights[2:-1:2] = 2.0

    return dx / 3.0 * float(np.dot(y, weights))
